### ISSUE TITLE
README doesn't explain what the project is

### ISSUE THREAD

**Issue by mboersma** [spectrocloud/cluster-api-provider-maas#19]
From the CAPI meeting, I noticed the link to this project and followed it, but I'm still clueless as to what's here after digesting the README.

It would be helpful if the term "MaaS" were explicitly defined once at the top of the README.md file. Also, please include a sentence or two explaining specifically what the project is, such as "Spectro Cloud provider for the Canonical Metal-as-a-Service interface." Links to more info are also helpful.

**Comment by jzhoucliqr** [comment]
Thanks for the recommendation. @mboersma
