### ISSUE TITLE
MAAS provider not working with clusterctl version v1.0.3

### ISSUE THREAD

**Issue by roshpr** [spectrocloud/cluster-api-provider-maas#34]
The MAAS provider is not working with the latest clusterctl version 1.0.3. We get the following error while using clusterctl
Fetching providers
Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha4 for provider infrastructure-maas

DO we plan to support MAAS provider for the latest version of clusterctl?

**Comment by sadysnaat** [comment]
Should be closed by #36

**Comment by roshpr** [comment]
The readme is not updated with the BetaV1 support and installation procedures. Can you please update it along with the code merge?

**Comment by sadysnaat** [comment]
@AmitSahastra i think release 0.3.0 is already done with v1alpha4 chages we should cut new release 0.4.0 for v1beta1

**Comment by levsha** [comment]
Any chances the changes will be published in a new release?

**Comment by nico-netminded** [comment]
When can we expect the 0.4.0 release?
